In [15]:
import numpy as np
import tensorflow as tf

In [16]:
a = np.array([[1.000920572024,2.000920572024,3.000920572024],[4.000920572024,5.000920572024,6.000920572024],[7.000920572024,8.000920572024,9.000920572024]])

In [17]:
np.matmul(a,a)

array([[ 30.01657284,  36.01933455,  42.02209627],
       [ 66.02485799,  81.0276197 ,  96.03038142],
       [102.03314314, 126.03590485, 150.03866657]])

In [18]:
tf.linalg.matmul(a,a)

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[ 30.01657284,  36.01933455,  42.02209627],
       [ 66.02485799,  81.0276197 ,  96.03038142],
       [102.03314314, 126.03590485, 150.03866657]])>